name: MyWorkflow1
on:
  push:
  workflow_dispatch:
jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
      - name: Generate image tag
        id: meta
        run: echo "image_tag=t${GITHUB_RUN_NUMBER}" >> "$GITHUB_OUTPUT"
      - name: Anil
        run: |
          echo "Build No >>>>>>>>>>>>>>>>>>>>>${GITHUB_RUN_NUMBER}"
          cat /etc/os-release
          whoami
          pwd
          cd
          ls -al
          mkdir oct9_2026
          ls -al
          cd  oct9_2026
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Ls
        run: |
          ls -al
  # hello2:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Sunil
  #       run: whoami
